name: Commitlint Workflow
concurrency:
  group: ci-${{ github.ref }}-commitlint
  cancel-in-progress: true

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    branches:
      - main

jobs:
  lint-commit-messages:
    name: Run commitlint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          # this is needed to get one of the
          # commitlint invocations below (that
          # analyzes commits from --from to --to)
          # to work
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          
      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Configure pnpm cache
        id: pnpm-cache
        run: echo "STORE_PATH=${pnpm store path}" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Cache pnpm dependencies
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        # If we don't do this, commitlint throws
        # errors about not finding rules package
        # for commit message conventions
        run: pnpm i

      # Using env in steps below to pass
      # required values from GitHub context rather
      # than accessing properties from GitHub context
      # directly. GitHub Docs recommend
      # that this is better for security as it
      # mitigates against script injection attacks
      - name: Run commitlint on PR source branch commit messages
        env:
          basesha: ${{ github.event.pull_request.base.sha }}
          headsha: ${{ github.event.pull_request.head.sha }}
        run: pnpm commitlint --from $basesha --to $headsha --verbose

      - name: Run commitlint on PR Title and Description
        env:
          prtitle: ${{ github.event.pull_request.title }}
          prdescription: ${{ github.event.pull_request.body }}
        run: printf "$prtitle\n\n$prdescription" | pnpm commitlint
